server:
  port: 9011
spring:
  application:
    name: tensquare-manager
eureka:
  client:
    service-url:   #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    tensquare-base:     #自定义的名字——基础
      path: /base/**    #配置请求URL的请求规则
      serviceId: tensquare-base  #指定Eureka注册中心中的服务id
    tensquare-user:     #自定义的名字——用户
      path: /user/**    #配置请求URL的请求规则
      serviceId: tensquare-user
    tensquare-qa:     #自定义的名字——问答
      path: /qa/**    #配置请求URL的请求规则
      serviceId: tensquare-qa